### PR TITLE
Update runtime to 23.08, use ffmpeg from runtime

### PR DESCRIPTION
**Pull request by PunkPangolin**

### CODE REVIEW

**Comment by Eonfge** [comment]
@enzo1982 How is it going? I know that we've collaborated in the past, but it seems that you're quite busy nowadays. If you want, you could consider giving others maintainer access so that you don't have to carry the burden all by yourself.

**Comment by Eonfge** [comment]
bot, build

**Comment by Eonfge** [comment]
@PunkPangolin doesn't run for me;
```
[kevin@kevin-fedora-desktop ~]$ flatpak install --user https://dl.flathub.org/build-repo/73413/org.freac.freac.flatpakref

org.freac.freac permissions:
    ipc      network      pulseaudio      x11      devices      file access [1]      dbus access [2]

    [1] host, xdg-run/dconf, ~/.config/dconf:ro
    [2] ca.desrt.dconf


        ID                       Branch          Op         Remote               Download
 1. [✓] org.freac.freac          test            i          freac-origin         8.6 MB / 8.7 MB

Installation complete.
[kevin@kevin-fedora-desktop ~]$ flatpak run org.freac.freac 
bwrap: Can't mkdir /app/lib/ffmpeg: Read-only file system
error: ldconfig failed, exit status 256
[kevin@kevin-fedora-desktop ~]$ 
```

Here you can see how to implement ffmpeg-full:
https://github.com/flathub/com.valvesoftware.Steam/blob/2633f8bd01e253e33b4a0386968455175fa4abe2/com.valvesoftware.Steam.yml#L118

**Comment by PunkPangolin** [comment]
@Eonfge thank you for the link! For me, the build worked, but I probably made a mistake somewhere… Using lib/ffmpeg seems to require a `mkdir -p /app/lib/ffmpeg` in the build commands. But just enabling it without these instructions also works fine, so maybe this is unnecessary?

Edit: Tenacity also defines the extension without further details, so I guess it works this way: https://github.com/flathub/org.tenacityaudio.Tenacity/blob/master/org.tenacityaudio.Tenacity.yaml

**Comment by enzo1982** [comment]
Hi folks, thank you for the PR and sorry for responding only now. Indeed, I was quite busy with other stuff recently and didn't have much time to spend working on fre:ac. I hope to get back to it now, slowly working through the backlog.

I initially added FFmpeg as a custom component, because the one included with the Flatpak runtime did not have all the codecs needed by fre:ac (most notably ALAC and WMA, but also some decoders for rarely used proprietary formats). However, this changed with the 23.08 runtime as all the required codecs were added in [this commit](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/commit/2321aafdf99cd5ac64168ab9cd674a5f0522fba1).

So I don't think we need the ffmpeg-full extension here anymore at all. The FFmpeg included with the base platform should suffice (already verified that with a local build).

@PunkPangolin could you remove the extension? I'll merge then after giving the build a quick test.

**Comment by PunkPangolin** [comment]
@enzo1982 I just removed ffmpeg-full, thank you!

**Comment by PunkPangolin** [comment]
bot, build

**Comment by PunkPangolin** [comment]
bot, build

**Comment by Newbytee** [comment]
Any chance this could be finished up? 22.08 is now EOL:
```
Info: runtime org.freedesktop.Platform branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   org.freac.freac
```

**Comment by enzo1982** [comment]
Merged to master. Thanks again and sorry for the delay!

I'll update some 3rd party library modules on the master branch now, then publish a release with the 23.08 runtime and immediately create another build using the new 24.08 runtime after that.

**Pull request merged**
